# Generated by Django 6.0.5 on 2026-07-14 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0002_department_is_archived'),
        ('django_forms_workflows', '0097_notificationlog_delivery_reconciliation'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editor_departments', models.ManyToManyField(blank=True, help_text="Departments whose members can edit this form's structure (fields, workflow, settings) in the visual builder. Does not affect who can submit the form or view its responses.", related_name='editable_forms', to='departments.department')),
                ('form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='django_forms_workflows.formdefinition')),
                ('viewer_departments', models.ManyToManyField(blank=True, help_text="Departments whose members can view every submission to this form, at any time — independent of whether they're an assigned approver on any specific workflow stage. Does not grant edit access to the form itself.", related_name='viewable_forms', to='departments.department')),
            ],
        ),
    ]
