# Generated by Django 6.0.5 on 2026-07-14 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formpermissions',
            options={'permissions': [('can_edit_any_form', 'Can edit any form, bypassing department scoping')]},
        ),
    ]
