# Generated by Django 6.0.5 on 2026-07-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0002_alter_formpermissions_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministratorPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('can_invite_to_any_department', 'Can invite users to any department'), ('can_edit_any_form', 'Can edit any form, bypassing department-level form scoping.')],
            },
        ),
        migrations.AlterModelOptions(
            name='formpermissions',
            options={},
        ),
    ]
