# Generated by Django 6.0.5 on 2026-07-14 12:41

import permissions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0002_alter_formpermissions_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministratorPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [(permissions.models.AdministratorPermission['CAN_INVITE_TO_ANY_DEPARTMENT'], 'Can invite users to any department'), (permissions.models.AdministratorPermission['CAN_EDIT_ANY_FORM'], 'Can edit any form, bypassing department-level form scoping.')],
            },
        ),
        migrations.AlterModelOptions(
            name='formpermissions',
            options={},
        ),
    ]
