# Generated by Django 6.0.5 on 2026-07-16 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0003_administratorpermissions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administratorpermissions',
            options={},
        ),
    ]
