# Generated by Django 6.0.5 on 2026-07-16 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0004_alter_administratorpermissions_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdministratorPermissions',
        ),
    ]
