# Generated by Django 6.0.5 on 2026-07-20 12:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0005_delete_administratorpermissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='formpermissions',
            name='editor_users',
            field=models.ManyToManyField(blank=True, help_text="Individual users who can edit this form's structure, independent of department membership — in addition to, not instead of, whoever qualifies via editor_departments.", related_name='editable_forms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formpermissions',
            name='viewer_users',
            field=models.ManyToManyField(blank=True, help_text='Individual users who can view every submission to this form, at any time, independent of department membership — in addition to, not instead of, whoever qualifies via viewer_departments.', related_name='viewable_forms', to=settings.AUTH_USER_MODEL),
        ),
    ]
