# Generated by Django 6.0.5 on 2026-07-21 14:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0005_alter_department_options'),
        ('permissions', '0006_formpermissions_editor_users_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formpermissions',
            name='viewer_departments',
        ),
        migrations.RemoveField(
            model_name='formpermissions',
            name='viewer_users',
        ),
        migrations.AddField(
            model_name='formpermissions',
            name='submission_viewer_users',
            field=models.ManyToManyField(blank=True, help_text='Individual users who can view every submission to this form, at any time. Nobody gets this via department membership, no matter how the form is scoped for editing — an explicit, minimum-necessary, per-person grant only.', related_name='viewable_forms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='formpermissions',
            name='editor_departments',
            field=models.ManyToManyField(blank=True, help_text="Members of the selected departments that have been assigned the blanket `Can edit forms` permissions will be able to edit this form. Leave this blank if you don't want any blanket permissions added to this form.", related_name='editable_forms', to='departments.department'),
        ),
    ]
