"""
Django settings for forms_manager project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from decouple import config

from accounts.utils import parse_domain_allowlist

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

AUTH_USER_MODEL = "accounts.User"

# Where LoginView sends users after a successful login with no ?next= —
# defaults to /accounts/profile/, which doesn't exist in this project.
LOGIN_REDIRECT_URL = "/"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)

ALLOWED_HOSTS = ["localhost", "127.0.0.1"]
USER_EMAIL_DOMAINS = config(
    "USER_EMAIL_DOMAINS", default="", cast=parse_domain_allowlist
)

if DEBUG:
    # Prints the decoded body rather than raw MIME — the raw source
    # quoted-printable-wraps long lines (e.g. password reset links), which
    # corrupts them when copy-pasted for manual testing.
    EMAIL_BACKEND = "core.email_backends.ReadableConsoleEmailBackend"


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # django-forms-workflows
    "nested_admin",
    "crispy_forms",
    "crispy_bootstrap5",
    "django_forms_workflows",
    "guardian",
    "treebeard",
    # non package
    "accounts",
    "builder_overrides",
    "core",
    "departments",
    "permissions",
]

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "guardian.backends.ObjectPermissionBackend",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "forms_manager.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        # Checked before each app's own templates/ dir (APP_DIRS below),
        # regardless of INSTALLED_APPS order — this is what lets our
        # registration/*.html and django_forms_workflows/base.html here
        # override the same-named templates shipped by django.contrib.admin
        # and django_forms_workflows.
        "DIRS": [BASE_DIR / "core" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django_forms_workflows.context_processors.forms_workflows",
                "permissions.context_processors.user_roles",
            ],
        },
    },
]

WSGI_APPLICATION = "forms_manager.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "static"

# Checked by FileSystemFinder, which runs before AppDirectoriesFinder in the
# default STATICFILES_FINDERS order — this is what lets a same-relative-path
# file placed here override one shipped inside an app's own static/ dir
# (e.g. django_forms_workflows/js/form-builder.js). There's no
# APP_DIRS-style "project dir checked first" for static files the way
# TEMPLATES["DIRS"] gives templates; this is the equivalent. Not
# core/static/ itself — that's also picked up by AppDirectoriesFinder (via
# INSTALLED_APPS, where django_forms_workflows sorts before core), which
# would still resolve to the *package's* copy first.
STATICFILES_DIRS = [BASE_DIR / "static_overrides"]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Django-forms-workflows
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"
