# Generated by Django 6.0.5 on 2026-07-14 16:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Your email address, used to sign in.', max_length=150, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='email'),
        ),
    ]
