# Generated by Django 6.0.5 on 2026-07-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
