# Generated by Django 6.0.5 on 2026-07-14 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_department_is_archived'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'permissions': [('can_invite_to_any_department', 'Can invite users to any department')]},
        ),
    ]
