# Generated by Django 6.0.5 on 2026-07-14 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_alter_department_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={},
        ),
    ]
