# Generated by Django 6.0.5 on 2026-07-17 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_alter_department_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'permissions': [('can_create_forms', 'Can create forms for this department'), ('can_edit_forms', "Can edit this department's forms"), ('can_archive_forms', "Can archive this department's forms"), ('can_create_workflows', "Can create workflows for this department's forms"), ('can_edit_workflows', "Can edit this department's workflows"), ('can_archive_workflows', "Can archive this department's workflows")]},
        ),
    ]
