# Generated by Django 6.0.5 on 2026-07-17 11:57

import departments.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_alter_department_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'permissions': [(departments.models.DepartmentPermission['CAN_CREATE_FORMS'], 'Can create forms for this department'), (departments.models.DepartmentPermission['CAN_EDIT_FORMS'], "Can edit this department's forms"), (departments.models.DepartmentPermission['CAN_ARCHIVE_FORMS'], "Can archive this department's forms"), (departments.models.DepartmentPermission['CAN_CREATE_WORKFLOWS'], "Can create workflows for this department's forms"), (departments.models.DepartmentPermission['CAN_EDIT_WORKFLOWS'], "Can edit this department's workflows"), (departments.models.DepartmentPermission['CAN_ARCHIVE_WORKFLOWS'], "Can archive this department's workflows")]},
        ),
    ]
