# Generated by Django 6.0.5 on 2026-07-21 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0005_alter_department_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'permissions': [('can_manage_forms', "Can create, edit, and archive this department's forms"), ('can_manage_workflows', "Can create, edit, and archive this department's workflows")]},
        ),
    ]
